### ISSUE TITLE
Непонятно, как запускать тесты

### ISSUE THREAD

**Issue by ashumkin** [wirenboard/wb-nm-helper#114]
Я хочу исправить ошибку, описанную в https://support.wirenboard.com/t/wb-connection-manager-ne-podderzhivaet-normalno-storonnie-straniczy-po-https/22018/ \
И даже уже исправил, но прежде, чем сделать PR, хотелось бы запустить тесты, чтобы убедиться, что ничего не сломалось, да и добавить тест на добавленную при исправлении функцию.

Но мне совершенно непонятно, как запускать тесты, при том, что они как будто есть, но `python3 -m unittest test` ни в корне репозитория, ни в каталоге `tests`, не запускают их.

К тому же нет файла с зависимостями проекта.

Можете добавить недостающее описание для нового человека в проекте?

**Comment by sikmir** [comment]
Тесты будут запущены при сборке deb пакета:
```sh
$ wget https://raw.githubusercontent.com/wirenboard/wirenboard/refs/heads/master/wbdev
$ chmod +x wbdev
$ ./wbdev cdeb
```

**Comment by ashumkin** [comment]
т.е. отдельных тестов проекта нет?

**Comment by sikmir** [comment]
> т.е. отдельных тестов проекта нет?

Есть, вот тут https://github.com/wirenboard/wb-nm-helper/tree/main/tests, они и будут запущены при сборке.

**Comment by ashumkin** [comment]
я имел в виду запуск тестов "автономно"

**Comment by sikmir** [comment]
> я имел в виду запуск тестов "автономно"

можно конечно все зависимости установить вручную, но рекомендуется все таки использовать докер, с ним сильно проще.

**Comment by ashumkin** [comment]
мне надо Вам рассказывать, что сильно проще - это когда у тебя есть исходники, ты их правишь и тут же запускаешь тесты, чтобы убедиться, что они проходят?.. при этом не надо ничего коммитить, пушить и ждать...

Вы же предлагаете какую-то "магическую" команду, которая непонятно что делает, непонятно откуда берёт исходники и непонятно как запускает какие-то тесты. Причём, я догадываюсь, что запускаются ВСЕ возможные (интеграционные?) тесты, хотя я изменяю один пакет... я не считаю это эффективным и нужным тогда, когда я правлю лишь один изолированный пакет... Вы предлагаете другой уровень из пирамиды тестирования, когда я прошу нижний...

**Comment by sikmir** [comment]
> при этом не надо ничего коммитить, пушить и ждать...

Используя wbdev также не нужно ничего коммитить, все происходит локально.

> Вы же предлагаете какую-то "магическую" команду, которая непонятно что делает, непонятно откуда берёт исходники и непонятно как запускает какие-то тесты.

По сути там в контейнере запускается дебиановский [sbuild](https://wiki.debian.org/sbuild), исходники локальные, wbdev сам их не берет ниоткуда, тесты запускаются через [dh_auto_test](https://manpages.debian.org/testing/debhelper/dh_auto_test.1.en.html).

> Причём, я догадываюсь, что запускаются ВСЕ возможные (интеграционные?) тесты, хотя я изменяю один пакет...

Нет, это не так, запускаются именно локальные юнит тесты данного пакета.

**Comment by ashumkin** [comment]
тааак-с )) 
shame on me
я поторопился делать заявления...

я подразобрался, посмотрел, запустил: запускается shell в контейнере, к которому подмонтированы каталоги с исходниками (нашёл при этом пару багов в своих .bashrc-файлах), однако, само ничего не запускается...

какой командой надо запустить тесты? ))

**Comment by ashumkin** [comment]
```
$ dh_auto_test 
dh_auto_test: warning: Please use the third-party "pybuild" build system instead of python-distutils
dh_auto_test: warning: This feature will be removed in compat 12.
```
```
pybuild
```

```
$ pytest
```
тоже падают с ошибками 
```
ModuleNotFoundError: No module named 'pycurl'                                                                                                                                
ModuleNotFoundError: No module named 'dbus'                                           
```

**Comment by sikmir** [comment]
Нет, вручную не надо ничего вызывать, оно все само запустит. Вот пример:
```sh
$ ./wbdev cdeb
<...>
   dh_auto_test -i -O--buildsystem=pybuild
I: pybuild base:232: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_wb-nm-helper/build; python3.9 -m pytest
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.1.2, pluggy-0.13.0
rootdir: /<<PKGBUILDDIR>>
plugins: testinfra-8.1.0, cov-2.10.1
collected 152 items

tests/test_connection_checker.py ..............                          [  9%]
tests/test_connection_manager_units.py ................................. [ 30%]
........................................................................ [ 78%]
...................                                                      [ 90%]
tests/test_mqtt_nm_helper.py .                                           [ 91%]
tests/test_network_interfaces_adapter.py .....                           [ 94%]
tests/test_network_manager_adapter.py ....                               [ 97%]
tests/test_nm_helper.py ....                                             [100%]

=============================== warnings summary ===============================
../../../../../../usr/lib/python3/dist-packages/dbusmock/mockobject.py:14
  /usr/lib/python3/dist-packages/dbusmock/mockobject.py:14: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

../../../../../../usr/lib/python3/dist-packages/dbus/service.py:35
  /usr/lib/python3/dist-packages/dbus/service.py:35: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Sequence

../../../../../../usr/lib/python3/dist-packages/dbus/decorators.py:330
  /usr/lib/python3/dist-packages/dbus/decorators.py:330: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    args = inspect.getargspec(func)[0]

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================= 152 passed, 3 warnings in 4.91s ========================
<...>
```

**Comment by ashumkin** [comment]
а, я пока ковырялся, пропустил аргумент `cdeb`... спасибо

оно, конечно, удобно, но долго... каждый прогон тестов ТАКИМ образом занимает 1.5 минуты драгоценного времени )) (при том, что прогон самих тестов пакета - это ~5 секунд)... overhead значительный...
